#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/python3

start_service() {
    if [ "$(uci get srunpy.@srunpy[0].enable)" == "1" ]; then
        local host=$(uci get srunpy.@srunpy[0].host)
        local protcol=$(uci get srunpy.@srunpy[0].protcol)
        local sleeptime=$(uci get srunpy.@srunpy[0].sleeptime)
        local ssl_verify=$(uci get srunpy.@srunpy[0].ssl_verify)
        if [ "$ssl_verify" != "1" ]; then
            ssl_verify="0"
        fi
        local username=$(uci get srunpy.@account[0].username)
        local password=$(uci get srunpy.@account[0].password)
        procd_open_instance
        procd_set_param command "$PROG" /lib/srunpy/AutoLogin.py --host $host --protcol $protcol --username $username --password $password --sleeptime $sleeptime --ssl_verify $ssl_verify
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn 600 5 3
        procd_set_param pidfile /var/run/srunpy.pid
        procd_close_instance
    fi
}